hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    # firewall_names: [oauth]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        youtube:
            type:                google
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               "email profile https://www.googleapis.com/auth/youtube"
            options:
                display: popup
                csrf: true
                refresh_on_expire: true
                access_type: offline
        spotify:
            type:                spotify
            client_id:           '%env(SPOTIFY_CLIENT_ID)%'
            client_secret:       '%env(SPOTIFY_CLIENT_SECRET)%'
            scope:               "user-read-email playlist-read-private playlist-modify-private playlist-modify-public" 
            options:
                csrf: true
                refresh_on_expire: true
        
